"""
Django settings for SmartTravel project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from celery.schedules import crontab

load_dotenv()

SECRET_KEY = os.getenv('SECRET_KEY')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ["api.atlasai.ro", "127.0.0.1", "localhost", "backend", "apiv2.atlasai.ro"] #TODO!!!

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'travel_planner',
    'social_automation',
    'ecommerce_core',
    'ecommerce_trendyol',
    
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_celery_beat',
    'storages',  # Pentru AWS S3 TODO: check this
    
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth',
    'dj_rest_auth.registration',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",  # Adresa frontend-ului
    "http://localhost:5173",
    "http://10.41.28.23:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "https://atlasai.ro",
    "https://www.atlasai.ro",
    "http://atlasai.ro",
    "http://www.atlasai.ro",
    "https://api.atlasai.ro",
    "http://api.atlasai.ro",
    "https://apiv2.atlasai.ro",
    "http://apiv2.atlasai.ro",
    "https://social.atlasai.ro",
    "http://social.atlasai.ro",
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:3002",
    "https://love-tour.atlasai.ro",
    "http://love-tour.atlasai.ro"
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://10.41.28.23:5173",
    "https://atlasai.ro",
    "https://www.atlasai.ro",
    "http://atlasai.ro",
    "http://www.atlasai.ro",
    "https://api.atlasai.ro",
    "http://api.atlasai.ro",
    "https://apiv2.atlasai.ro",
    "http://apiv2.atlasai.ro",
    "https://social.atlasai.ro",
    "http://social.atlasai.ro",
    "http://localhost:3000",
    "https://love-tour.atlasai.ro",
    "http://love-tour.atlasai.ro"
]
CORS_ALLOW_CREDENTIALS = True

# ✅ Allow API endpoints to work without CSRF
CSRF_COOKIE_NAME = "csrftoken"
CSRF_COOKIE_HTTPONLY = False

MIDDLEWARE.insert(0, 'corsheaders.middleware.CorsMiddleware')

ROOT_URLCONF = 'SmartTravel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SmartTravel.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASS'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'

# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1 # Necesar pentru django-allauth
ACCOUNT_EMAIL_VERIFICATION = 'none' # Pentru simplitate, nu cerem verificare pe email la înregistrare
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_REQUIRED = True

# Specificăm serializer-ul nostru custom pentru a adăuga câmpul 'company_name' la înregistrare
REST_AUTH = {
    'REGISTER_SERIALIZER': 'social_automation.serializers.CustomRegisterSerializer',
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# --- CELERY SETTINGS ---
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Bucharest' # Setează fusul orar corect

# --- CONFIGURAȚIE AWS S3 PENTRU STOCARE MEDIA ---
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
}

# Credențialele și configurația bucket-ului S3
#AWS_DEFAULT_ACL = 'public-read'
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME') # ex: 'atlasai-media-storage'
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME') # ex: 'eu-central-1'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400', # Cache-ul pentru fișiere: 24 de ore
}

# Directorul unde se vor salva fișierele de media în bucket
AWS_LOCATION = 'media'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'

CELERY_BEAT_SCHEDULE = {
    'refresh-trendyol-categories-cache-nightly': {
        'task': 'ecommerce_trendyol.tasks.refresh_trendyol_categories_cache',
        'schedule': crontab(hour=3, minute=0), # Rulează în fiecare noapte la 03:00
        'args': (),
    },

    'sync-trendyol-orders-every-15-mins': {
        'task': 'ecommerce_trendyol.tasks.sync_trendyol_orders_periodic',
        'schedule': crontab(minute='*/15'), # La fiecare 15 minute
    },

    'sync-trendyol-claims-every-1-hour': {
        'task': 'ecommerce_trendyol.tasks.sync_trendyol_claims_periodic',
        'schedule': crontab(hour=1),
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1", # Folosim DB 1 (0 e pentru Celery)
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# Cloudinary
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME')
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET')