# Generated by Django 5.1.3 on 2025-10-29 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('trendyol', 'Trendyol'), ('emag', 'eMAG')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('seller_id', models.CharField(max_length=100)),
                ('api_key', models.TextField(blank=True)),
                ('api_secret', models.TextField(blank=True)),
                ('store_front_code', models.CharField(default='RO', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cont Marketplace',
                'verbose_name_plural': 'Conturi Marketplace',
                'unique_together': {('user', 'seller_id', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='SKU-ul tău intern, unic pentru produsul de bază.', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(help_text='Numele brandului tău intern.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produs (PIM)',
                'verbose_name_plural': 'Produse (PIM)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='SKU-ul unic al variantei (ex: TR-ROSU-M).', max_length=100, unique=True)),
                ('barcode', models.CharField(db_index=True, max_length=100)),
                ('attributes', models.JSONField(default=dict, help_text='Ex: {"culoare": "Roșu", "marime": "M"}')),
                ('images', models.JSONField(default=list, help_text='Listă de URL-uri ale imaginilor.')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Stocul fizic real.')),
                ('price', models.DecimalField(decimal_places=2, help_text="Prețul 'master' de vânzare.", max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ecommerce_core.product')),
            ],
            options={
                'verbose_name': 'Variantă Produs (PIM)',
                'verbose_name_plural': 'Variante Produse (PIM)',
                'ordering': ['product', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_listing_id', models.CharField(blank=True, db_index=True, help_text='ID-ul de la Trendyol (batchRequestId inițial, apoi alt ID)', max_length=100)),
                ('platform_category_id', models.CharField(max_length=50)),
                ('platform_brand_id', models.CharField(max_length=50)),
                ('platform_attributes', models.JSONField(default=dict, help_text='Atributele formatate pentru API-ul platformei.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_create', 'Așteaptă Creare'), ('pending_update', 'Așteaptă Actualizare'), ('active', 'Activ'), ('failed', 'Eșuat'), ('archived', 'Arhivat')], default='draft', max_length=20)),
                ('last_sync_status', models.TextField(blank=True, help_text='Ultimele erori sau mesaje de succes de la API.')),
                ('stock_override', models.PositiveIntegerField(blank=True, help_text='Opțional: Setează un stoc fix de trimis (ex: 50).', null=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Opțional: Setează un preț diferit pentru această platformă.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='ecommerce_core.marketplaceaccount')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='ecommerce_core.productvariant')),
            ],
            options={
                'verbose_name': 'Listare Marketplace',
                'verbose_name_plural': 'Listări Marketplace',
                'unique_together': {('variant', 'platform_account')},
            },
        ),
    ]
