# Generated by Django 5.1.3 on 2025-11-22 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_order_number', models.CharField(db_index=True, help_text='Numărul comenzii clientului (orderNumber).', max_length=100)),
                ('platform_package_id', models.CharField(db_index=True, help_text='ID-ul pachetului (shipmentPackageId) - Cheia principală pentru Trendyol.', max_length=100, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RON', max_length=3)),
                ('customer_first_name', models.CharField(blank=True, max_length=100)),
                ('customer_last_name', models.CharField(blank=True, max_length=100)),
                ('customer_email', models.CharField(blank=True, max_length=255)),
                ('shipping_address', models.JSONField(default=dict)),
                ('invoice_address', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('Created', 'Creată'), ('Picking', 'În Pregătire'), ('Invoiced', 'Facturată'), ('Shipped', 'Expediată'), ('Cancelled', 'Anulată'), ('Delivered', 'Livrată'), ('UnDelivered', 'Nelivrată'), ('Returned', 'Returnată'), ('Unknown', 'Necunoscut')], default='Created', max_length=50)),
                ('order_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ecommerce_core.marketplaceaccount')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_order_line_id', models.CharField(help_text='ID unic al liniei (orderLineId). Necesar pentru split/cancel.', max_length=100)),
                ('sku', models.CharField(help_text='SKU-ul așa cum a venit din platformă (merchantSku).', max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(default='Created', max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce_core.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='ecommerce_core.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('platform_order_number', models.CharField(max_length=100)),
                ('claim_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Created', 'Creat'), ('WaitingInAction', 'Așteaptă Acțiune'), ('Accepted', 'Acceptat'), ('Rejected', 'Respins'), ('Cancelled', 'Anulat'), ('Unresolved', 'Nerezolvat'), ('InAnalysis', 'În Analiză')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='ecommerce_core.order')),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='ecommerce_core.marketplaceaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_line_item_id', models.CharField(max_length=100, unique=True)),
                ('sku', models.CharField(max_length=100)),
                ('customer_reason', models.CharField(blank=True, max_length=255)),
                ('customer_note', models.TextField(blank=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce_core.returnrequest')),
            ],
        ),
    ]
