# Generated by Django 5.1.3 on 2025-11-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_core', '0002_order_orderlineitem_returnrequest_returnlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='delivery_duration',
            field=models.PositiveIntegerField(default=2, help_text='Durata de livrare promisă (zile).'),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='returning_address_id',
            field=models.BigIntegerField(blank=True, help_text='ID-ul adresei de retur de pe Trendyol. Dacă e gol, se caută automat una default.', null=True),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='shipment_address_id',
            field=models.BigIntegerField(blank=True, help_text='ID-ul adresei de expediere de pe Trendyol. Dacă e gol, se caută automat una default.', null=True),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='vat_rate',
            field=models.PositiveIntegerField(default=21, help_text='Cota TVA'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prețul întreg (tăiat). Dacă e gol, se va folosi prețul de vânzare.', max_digits=10, null=True),
        ),
    ]
