# Generated by Django 5.1.3 on 2025-11-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_core', '0003_marketplacelisting_delivery_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacelisting',
            name='delivery_duration',
        ),
    ]
