# Generated by Django 5.1.3 on 2025-11-22 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_core', '0004_remove_marketplacelisting_delivery_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='type',
            field=models.CharField(choices=[('simple', 'Produs Simplu'), ('bundle', 'Bundle / Set')], default='simple', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Stoc fizic (simple) sau calculat (bundle).'),
        ),
        migrations.CreateModel(
            name='BundleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bundle_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_components', to='ecommerce_core.productvariant')),
                ('component_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='included_in_bundles', to='ecommerce_core.productvariant')),
            ],
            options={
                'verbose_name': 'Componentă Bundle',
                'unique_together': {('bundle_variant', 'component_variant')},
            },
        ),
    ]
